# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: ğŸš€ Deploy app to stagging

on:
  push:
    branches: ["stagging"]

jobs:
  build:
    name: ğŸš€ Stagging Deploy
    runs-on: self-hosted

    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v3
      - name: ğŸ—ï¸ Build Project
        run: |
          npm i
          npm run build
      - name: ğŸ“‚ Sync files
        run: rsync -rp ./dist /home/ubuntu/localpro-backend-runner/localpro/localpro/localpro/client
